### ISSUE TITLE
Missing close() method

### ISSUE THREAD

**Issue by menchyshyn** [postpop/videoreader#4]
Hi,
Videoreader is a very nice abstraction wrapper over plain OpenCV routines. It has greatly simplified my data loading for the video datasets. Thank you for sharing!
I have found that method `close()` mentioned in the README.md is missing. And I see that in the class docstring you propose explicit releasing of the resources with `del(vr)`. So I believe it's just a documentation inconsistency. For myself, I prefer adding the method `close()`, but you decide the way it's have to be.
Cheers!

**Comment by postpop** [comment]
Hi, thanks for pointing this out! I'll add a `close()` method.
