### ISSUE TITLE
frame_width and frame_height properties are permuted

### ISSUE THREAD

**Issue by menchyshyn** [postpop/videoreader#5]
Hi,
Didn't expect from myself to enter two issues a day) I think these are just copy-paste typos
`
@property
def frame_width(self):
    return int(self._vr.get(cv2.CAP_PROP_FRAME_HEIGHT))

@property
def frame_height(self):
    return int(self._vr.get(cv2.CAP_PROP_FRAME_WIDTH))
`
Thank you

**Comment by postpop** [comment]
Hi again, thanks for spotting this. Will fix this in the next release!
